---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0751'
  with_items:
    - /var/www/
    - "{{ dirs.server.apps }}"
    - "{{ dirs.server.apps_data }}"
  tags: dirs

- name: Fix www ownership
  file:
    path: "{{ item }}"
    owner: www-data
    group: www-data
  with_items:
    - /var/www/
    - "{{ dirs.server.apps }}"
    - "{{ dirs.server.apps_data }}"
  tags: dirs

- name: System daemon-reload
  systemd:
    daemon_reload: yes
  tags: dirs

- name: System tmpfiles create
  ansible.builtin.command: systemd-tmpfiles --create
  tags: dirs
