---
roles:
  - src: geerlingguy.nodejs
  - src: geerlingguy.docker
  - src: geerlingguy.composer
  - src: oefenweb.yarn
  - src: datadog.datadog
  - src: ebbba.bigbluebutton

collections:
  - name: community.general
